### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by pippinmole**

### CODE REVIEW

**Comment by pippinmole** [comment]
I'm not going to include it in the README because I don't know enough to know if it will affect anything, but it should be `git push heroku main` and not `git push heroku master` - Heroku and Git have noted that they are moving away from the use of the word master.

**Comment by joaorafaelm** [comment]
Hi, thanks for your PR. This repo is actually not related to heroku, I've been using it to automatically deploy to vultr, using docker deploy and to automatically update strategies based on gh actions. take a look at the gh actions to understand how it works https://github.com/p-zombie/freqtrade/tree/master/.github/workflows
Unfortunately I did a bad job at documenting how to setup, but I'll write a decent readme soon.

Here is an overview of how it works right now:
First of all, you need a docker host to deploy the app, like https://www.vultr.com/docs/one-click-docker/ or any other provider you want.
Then, you need to have a [docker hub account](https://hub.docker.com)
Optionally, you may setup a telegram bot to receive deployment messages.

Once you have everything above, fork the repo, then you'll need to setup a few [GitHub secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) to make it work:

secrets.DOCKER_USERNAME -- docker hub username
secrets.DOCKER_PASSWORD -- docker hub password
secrets.DOCKER_HOST -- used by https://github.com/wshihadeh/docker-deployment-action
secrets.DOCKER_SSH_PRIVATE_KEY -- used by https://github.com/wshihadeh/docker-deployment-action
secrets.DOCKER_SSH_PUBLIC_KEY -- used by https://github.com/wshihadeh/docker-deployment-action 
secrets.TELEGRAM_TO -- chat id which will receive deployment messages
secrets.TELEGRAM_TOKEN -- telegram bot token
secrets.GH_PAT -- personal GitHub token, used by https://github.com/p-zombie/freqtrade/blob/master/.github/workflows/update_strat.yml

Every-time you commit something to the repo, it will trigger a new docker build and push the image to docker hub (https://github.com/p-zombie/freqtrade/blob/master/.github/workflows/main.yml), and it will deploy [production.yml](https://github.com/p-zombie/freqtrade/blob/master/production.yml) to the host you setup using a [docker deployment action](https://github.com/wshihadeh/docker-deployment-action). PS; you may need to modify production.yml and change the image name to match your docker hub username, if not, it will use the image under my username.

I also added a scheduled job to run using GitHub actions: https://github.com/p-zombie/freqtrade/blob/master/.github/workflows/update_strat.yml
it is set to run every minute but GitHub actually runs it about every 5 minutes; it pulls strategies, blacklists and pairlist files from https://github.com/iterativv/NostalgiaForInfinity and if the files changed, it will commit to the repo, which will trigger a new deploy and send a message in the telegram chat specified in the secrets.

That's about it, the hardest part is probably setting up the secrets for docker-deployment-action, but it should be pretty straightforward. I also added a [docker prune file](https://github.com/p-zombie/freqtrade/blob/master/docker-prune) to prevent docker cache consuming all space in your docker host, copy to your docker host and run `chmod +x docker-prune && mv docker-prune /etc/cron.daily` and it should run every day.

if you plan to run it locally, it works exactly as the heroku repo, take a look at the [makefile](https://github.com/p-zombie/freqtrade/blob/master/Makefile) to check the available commands, or simply run make or make help to get a list of commands.

**Comment by pippinmole** [comment]
Hi,

I tried adding the user secrets, however you cannot use special characters for GitHub secrets

Screenshot 2022-01-01 at 23 25 28
.

**Comment by joaorafaelm** [comment]
you don't need to add secrets. to the secret name it should be only the actual name, ex: DOCKER_USERNAME, DOCKER_PASSWORD etc.

**Pull request closed without merging**
